/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.librarysystemmanagement;

import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.SwingUtilities;

/**
 * Represents the initial page of the library system GUI. Allows users to choose
 * between librarian and student options, and select language preferences.
 * Handles the creation of the initial page GUI and updating UI based on
 * language selection.
 *
 * @author Olivier
 */
public class InitialPage extends javax.swing.JFrame {

    private LibraryController libraryController;
    private ResourceBundle bundle;
    private Locale currentLocale;

    /**
     * Creates a new instance of InitialPage.
     *
     * @param libraryController The LibraryController for managing library
     * operations.
     */
    public InitialPage(LibraryController libraryController) {
       // initComponents();
        this.libraryController = libraryController;
        
       // this.currentLocale = new Locale("en"); // Set to default locale initially
       // this.bundle = ResourceBundle.getBundle("initialPage", currentLocale);


        setTitle("initialPage.title");
        setSize(400, 200);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        createGUI();
    }

    /**
     * Initializes the graphical user interface components.
     */
    private void createGUI() {
        // Create the main panel
        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayout(2, 1));

        // Create buttons for librarian and student
        JButton librarianButton = new JButton("Librarian");
        JButton studentButton = new JButton("Student");

        // Add action listeners for librarian and student buttons
        librarianButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                openLoginForm("Librarian");
            }
        });

        studentButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                openLoginForm("Student");
            }
        });

        //Create radio buttons for language selection
//        JRadioButton englishButton = new JRadioButton("English");
//        JRadioButton frenchButton = new JRadioButton("French");

        // Set English as the default selected language
//        englishButton.setSelected(true);

//        englishButton.addActionListener(e -> updateLocale(Locale.ENGLISH));
//        frenchButton.addActionListener(e -> updateLocale(Locale.FRENCH));

        // Add components to the main panel
        mainPanel.add(librarianButton);
        mainPanel.add(studentButton);
//        mainPanel.add(englishButton);
//        mainPanel.add(frenchButton);

        // Add the main panel to the frame
        add(mainPanel);
    }

    private void openLoginForm(String userType) {
        LoginForm loginForm = new LoginForm(userType, libraryController);
        loginForm.setVisible(true);
        // Optionally, you can hide the current frame if needed
        this.setVisible(false);
    }

//    private void updateLocale(Locale locale) {
//        currentLocale = locale;
//        bundle = ResourceBundle.getBundle("com.mycompany.librarysystemmanagement.resources.initialPage", currentLocale);
//        updateUI();
//    }

    /**
     * Updates the user interface based on the selected language.
     */
//    private void updateUI() {
//        setTitle(bundle.getString("initialPage.title"));
//
//         Iterate through components and update buttons based on language
//        Component[] components = getContentPane().getComponents();
//        for (Component component : components) {
//            if (component instanceof JButton) {
//                JButton button = (JButton) component;
//                String buttonKey = "initialPage." + button.getText().toLowerCase();
//                button.setText(bundle.getString(buttonKey));
//            }
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Main method to launch the application.
     *
     * @param args The command line arguments.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitialPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitialPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitialPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitialPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // Launch the GUI on the event dispatch thread
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                // Create tables and initialize the library controller
                DatabaseHandler.createTables();
                LibraryController controller = new LibraryController(new DatabaseHandler());

                // Create and display the initial page
                InitialPage initialPage = new InitialPage(controller);
                initialPage.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
